name = "CoulombIntegral"
uuid = "95871d0a-b0d4-4f82-9ec8-411977f2e218"
authors = ["Teemu JÃ¤rvinen <teemu.jarvinen@helsinki.fi> and contributors"]
version = "0.1.0"

[deps]
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
GaussQuadrature = "0.5"
ProgressMeter = "1.4"
TensorOperations = "3.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
