name = "CoulombIntegral"
uuid = "95871d0a-b0d4-4f82-9ec8-411977f2e218"
authors = ["Teemu JÃ¤rvinen <teemu.jarvinen@helsinki.fi> and contributors"]
version = "0.1.0"

[deps]
BarycentricInterpolation = "9eb6a62d-0ffa-5353-839e-400c605afeda"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
TensorOperations = "3.0"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
