name = "HKQM"
uuid = "95871d0a-b0d4-4f82-9ec8-411977f2e218"
authors = ["Teemu JÃ¤rvinen <teemu.jarvinen@helsinki.fi> and contributors"]
version = "0.2.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ForwardDiff = "0.10"
GaussQuadrature = "0.5"
Polynomials = "1.1"
ProgressMeter = "1.3"
QuadGK = "2.4"
Reexport = "0.2, 1.0"
SpecialFunctions = "0.10, 1.0"
StaticArrays = "0.12, 1.0"
TensorOperations = "3.0"
Unitful = "1.5"
UnitfulAtomic = "1.0"
Zygote = "0.5, 0.6"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
